title: GitHub Pages With Jekyll
author: Jason Coombs
email: jcoombs@risknerd.com
description: > # this means to ignore newlines until "baseurl:"
  Testing maketh man.
# social links
twitter_username: JasonCoombsCEO
github_username:  JasonCoombs

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
